### ISSUE TITLE
when time out situation,how to solve the animation view

### ISSUE THREAD

**Issue by ymmmvp** [rockerhieu/rv-adapter-endless#4]
sorry,my english is very poor.
i have found a situation that,when it excute loadmore method,but the network is bad or timeout.then the loading animation is still there.my solution is excute recycleview's scrollby().after excuting the method,the animaiton view is out of the screen.
do you have a good method to solve this?
forgive my poor english...

**Comment by rockerhieu** [comment]
If the network is timeout, it should throw an exception. You can try catch the exception and invoke a callback to stop the animation.
