### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by sooola** [rockerhieu/rv-adapter-endless#7]
hello,there is a bug when RecycleView using GridLayoutManager and set this headview 
        mGridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return position ==0 ? 3 : 1;
            }
        });
 the progressbar is on the left no center

**Comment by rockerhieu** [comment]
Mmmm, sorry but it sounds like the bug has nothing to do with `rv-adapter-endless`.

**Comment by sooola** [comment]
yeah,thanks u reply is other reason
